name: Build react basic
on:
  push:
    branches: ['main']
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Install yarn
      run: npm install yarn -g
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
  
